/* global Cesium */
Cesium.Ion.defaultAccessToken = undefined;

const ANALYST = "https://tushar2159.github.io/agentic-earth-intelligence/";
const demos = [
  {id:"pune",name:"Urban Change",region:"Pune · India",icon:"▦",lat:18.5204,lon:73.8567,type:"urban_change",dateA:"2020-01-01",dateB:"2026-12-31",description:"Indicative built-up spectral change over a public urban AOI."},
  {id:"ghats",name:"Vegetation Change",region:"Western Ghats · India",icon:"♧",lat:15.3173,lon:74.1240,type:"vegetation_change",dateA:"2020-01-01",dateB:"2026-12-31",description:"NDVI-based vegetation comparison over a public landscape."},
  {id:"reservoir",name:"Water Change",region:"Ujani Reservoir · India",icon:"≈",lat:18.0935,lon:75.1170,type:"water_change",dateA:"2020-01-01",dateB:"2026-12-31",description:"NDWI-based surface-water comparison over a public reservoir."},
  {id:"agriculture",name:"Seasonal Agriculture",region:"Punjab · India",icon:"⌁",lat:30.9010,lon:75.8573,type:"vegetation_change",dateA:"2025-01-01",dateB:"2025-10-31",description:"Seasonal vegetation signal over a public agricultural AOI."}
];
const places={pune:[18.5204,73.8567],bengaluru:[12.9716,77.5946],bangalore:[12.9716,77.5946],mumbai:[19.076,72.8777],delhi:[28.6139,77.209],dehradun:[30.3165,78.0322],manaus:[-3.119,-60.0217],"western ghats":[15.3173,74.124],"ujani reservoir":[18.0935,75.117]};

const viewer=new Cesium.Viewer("globe",{baseLayer:false,terrainProvider:new Cesium.EllipsoidTerrainProvider(),animation:false,timeline:false,baseLayerPicker:false,geocoder:false,homeButton:false,sceneModePicker:false,navigationHelpButton:false,fullscreenButton:false,selectionIndicator:false,infoBox:false,requestRenderMode:false});
viewer.scene.globe.enableLighting=false;viewer.scene.globe.showGroundAtmosphere=true;viewer.scene.skyAtmosphere.show=true;viewer.scene.backgroundColor=Cesium.Color.fromCssColorString("#02060b");
const imagery=viewer.imageryLayers.addImageryProvider(new Cesium.UrlTemplateImageryProvider({url:"https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",credit:new Cesium.Credit("Imagery © Esri"),maximumLevel:19}));
const route=viewer.entities.add({id:"demo-network",polyline:{positions:Cesium.Cartesian3.fromDegreesArray(demos.flatMap(p=>[p.lon,p.lat])),width:1.5,material:new Cesium.PolylineGlowMaterialProperty({glowPower:.18,color:Cesium.Color.fromCssColorString("#64f0d8").withAlpha(.6)})}});
const pulseStart=performance.now();
demos.forEach((item,index)=>viewer.entities.add({id:`demo-${item.id}`,position:Cesium.Cartesian3.fromDegrees(item.lon,item.lat),point:{pixelSize:new Cesium.CallbackProperty(()=>11+Math.sin((performance.now()-pulseStart)/420+index)*2,false),color:Cesium.Color.fromCssColorString("#64f0d8"),outlineColor:Cesium.Color.WHITE,outlineWidth:2},label:{text:`PUBLIC DEMO · ${item.region.toUpperCase()}`,font:"700 11px Manrope",showBackground:true,backgroundColor:Cesium.Color.fromCssColorString("#03101b").withAlpha(.84),pixelOffset:new Cesium.Cartesian2(0,-27),distanceDisplayCondition:new Cesium.DistanceDisplayCondition(0,8000000)}}));

let selected=null,aoiEntity=null,rotating=true;
const missions=document.getElementById("missions");
missions.innerHTML=demos.map(p=>`<button class="mission" data-id="${p.id}"><i>${p.icon}</i><span><b>${p.name}</b><small>PUBLIC DEMO · ${p.region}</small></span><span>›</span></button>`).join("");

function selectLocation(lat,lon,name="Selected point",fly=true){
  selected={lat:Number(lat),lon:Number(lon),name};const radius=Number(document.getElementById("radius").value);
  if(aoiEntity)viewer.entities.remove(aoiEntity);
  aoiEntity=viewer.entities.add({id:"analysis-aoi",name:"Analysis AOI",position:Cesium.Cartesian3.fromDegrees(selected.lon,selected.lat),ellipse:{semiMajorAxis:radius*1000,semiMinorAxis:radius*1000,material:Cesium.Color.fromCssColorString("#64f0d8").withAlpha(.16),outline:true,outlineColor:Cesium.Color.fromCssColorString("#64f0d8"),height:10},label:{text:`${radius} KM AOI`,font:"700 11px Manrope",showBackground:true,backgroundColor:Cesium.Color.fromCssColorString("#03101b").withAlpha(.88),pixelOffset:new Cesium.Cartesian2(0,-30)}});
  document.getElementById("selectedLocation").innerHTML=`<b>${name}</b><small>${selected.lat.toFixed(5)}°, ${selected.lon.toFixed(5)}° · ${radius} km radius</small>`;
  document.getElementById("runAnalysis").disabled=false;document.getElementById("statusTitle").textContent="AOI READY";document.getElementById("statusDetail").textContent="Review parameters, then launch the AI Analyst";
  rotating=false;document.querySelector('[data-layer="rotation"]').classList.remove("active");
  if(fly)viewer.camera.flyTo({destination:Cesium.Cartesian3.fromDegrees(selected.lon,selected.lat,Math.max(65000,radius*14000)),duration:1.8,orientation:{heading:0,pitch:Cesium.Math.toRadians(-62),roll:0}});
}

function chooseDemo(demo){
  document.querySelectorAll(".mission").forEach(b=>b.classList.toggle("active",b.dataset.id===demo.id));document.getElementById("analysisType").value=demo.type;document.getElementById("dateA").value=demo.dateA;document.getElementById("dateB").value=demo.dateB;
  document.getElementById("projectType").textContent="PUBLIC DEMO";document.getElementById("projectTitle").textContent=demo.name;document.getElementById("projectDescription").textContent=demo.description;document.getElementById("projectStack").innerHTML=["Public AOI","Sentinel-2","Spectral index","Cesium"].map(s=>`<span>${s}</span>`).join("");document.getElementById("projectDemo").href="#analysisForm";document.getElementById("projectDemo").textContent="Configure analysis ↓";document.getElementById("projectRepo").href="https://github.com/tushar2159/agentic-earth-intelligence";document.getElementById("projectCard").classList.add("open");selectLocation(demo.lat,demo.lon,demo.region);
}
missions.addEventListener("click",event=>{const button=event.target.closest(".mission");if(button)chooseDemo(demos.find(d=>d.id===button.dataset.id));});
document.getElementById("closeCard").addEventListener("click",()=>document.getElementById("projectCard").classList.remove("open"));document.getElementById("radius").addEventListener("change",()=>selected&&selectLocation(selected.lat,selected.lon,selected.name,false));

document.getElementById("locationForm").addEventListener("submit",event=>{event.preventDefault();const raw=document.getElementById("locationSearch").value.trim();const pair=raw.match(/^(-?\d+(?:\.\d+)?)\s*,\s*(-?\d+(?:\.\d+)?)$/);const found=pair?[Number(pair[1]),Number(pair[2])]:places[raw.toLowerCase()];const message=document.getElementById("searchMessage");if(!found||Math.abs(found[0])>90||Math.abs(found[1])>180){message.textContent="Location not found. Try a listed public place or valid latitude, longitude.";message.classList.add("error");return;}message.textContent="Location resolved without exposing a private geocoding key.";message.classList.remove("error");selectLocation(found[0],found[1],raw||"Coordinates");});
document.getElementById("analysisForm").addEventListener("submit",event=>{event.preventDefault();if(!selected)return;const a=document.getElementById("dateA").value,b=document.getElementById("dateB").value;if(!a||!b||a>=b){document.getElementById("statusTitle").textContent="CHECK DATES";document.getElementById("statusDetail").textContent="Date A must be earlier than Date B";return;}const params=new URLSearchParams({lat:selected.lat.toFixed(6),lon:selected.lon.toFixed(6),location:selected.name,radius_km:document.getElementById("radius").value,analysis:document.getElementById("analysisType").value,date_a:a,date_b:b,cloud:document.getElementById("cloud").value,confirm:"1"});location.href=`${ANALYST}?${params}`;});

const handler=new Cesium.ScreenSpaceEventHandler(viewer.scene.canvas);handler.setInputAction(movement=>{const picked=viewer.scene.pick(movement.position);if(picked?.id?.id?.startsWith("demo-")){chooseDemo(demos.find(d=>`demo-${d.id}`===picked.id.id));return;}const ray=viewer.camera.getPickRay(movement.position);const cartesian=ray&&viewer.scene.globe.pick(ray,viewer.scene);if(!cartesian)return;const c=Cesium.Cartographic.fromCartesian(cartesian);selectLocation(Cesium.Math.toDegrees(c.latitude),Cesium.Math.toDegrees(c.longitude),"Globe selection",false);},Cesium.ScreenSpaceEventType.LEFT_CLICK);
viewer.clock.shouldAnimate=true;viewer.clock.onTick.addEventListener(()=>{if(rotating&&viewer.camera.positionCartographic.height>2500000)viewer.camera.rotate(Cesium.Cartesian3.UNIT_Z,-0.00028)});
document.querySelector(".layers").addEventListener("click",e=>{const button=e.target.closest("button");if(!button)return;button.classList.toggle("active");const enabled=button.classList.contains("active");if(button.dataset.layer==="imagery")imagery.show=enabled;if(button.dataset.layer==="network")route.show=enabled;if(button.dataset.layer==="atmosphere"){viewer.scene.skyAtmosphere.show=enabled;viewer.scene.globe.showGroundAtmosphere=enabled}if(button.dataset.layer==="rotation")rotating=enabled;});
viewer.camera.setView({destination:Cesium.Cartesian3.fromDegrees(42,18,18500000),orientation:{heading:0,pitch:Cesium.Math.toRadians(-90),roll:0}});viewer.scene.postRender.addEventListener(()=>{const c=viewer.camera.positionCartographic;document.getElementById("coordinates").textContent=`${Cesium.Math.toDegrees(c.latitude).toFixed(2)}° · ${Cesium.Math.toDegrees(c.longitude).toFixed(2)}° · ${Math.round(c.height/1000).toLocaleString()} km`;});
