/* global Cesium */
Cesium.Ion.defaultAccessToken = undefined;

const projects = [
  {id:"pune",name:"Agentic Earth Intelligence",region:"Pune · India",icon:"◎",lat:18.5204,lon:73.8567,alt:850000,type:"FLAGSHIP · AGENTIC GEOAI",description:"A natural-language geospatial intelligence workspace with temporal satellite comparison, environmental data routing and traceable analytical execution.",stack:["FastAPI","React","MapLibre","STAC","Docker"],demo:"https://tushar2159.github.io/agentic-earth-intelligence/",repo:"https://github.com/tushar2159/agentic-earth-intelligence"},
  {id:"dehradun",name:"Earth Observation Systems",region:"Dehradun · India",icon:"◫",lat:30.3165,lon:78.0322,alt:750000,type:"REMOTE SENSING · GEOAI",description:"Earth-observation pipelines for temporal analytics, change detection, spatial validation and reproducible data engineering.",stack:["Sentinel","Rasterio","GeoPandas","PyTorch"],repo:"https://github.com/tushar2159/earth-observation-data-pipeline"},
  {id:"enschede",name:"Spatial Intelligence Research",region:"Enschede · Netherlands",icon:"⌘",lat:52.2215,lon:6.8937,alt:700000,type:"GEOINFORMATICS · RESEARCH",description:"Geospatial reasoning shaped by international training across IIRS–ISRO and ITC, University of Twente.",stack:["GIS","Remote Sensing","Spatial Analysis"],repo:"https://github.com/tushar2159"},
  {id:"global",name:"Production GeoAI Platforms",region:"UAE · Middle East",icon:"↗",lat:25.2048,lon:55.2708,alt:900000,type:"CLOUD · MODEL DELIVERY",description:"API-first analytical systems with typed contracts, containers, automated tests and observable release boundaries.",stack:["AWS","FastAPI","CI/CD","MLOps"],repo:"https://github.com/tushar2159/geoai-mlops-template"},
  {id:"usa",name:"Farm Boundary & Crop Type Intelligence",region:"USA · North America",icon:"▱",lat:38.9072,lon:-77.0369,alt:1100000,type:"AGRICULTURE · SEGMENTATION · CLASSIFICATION",description:"Earth-observation workflows for delineating agricultural fields and assigning crop-type classes with GIS-ready outputs.",stack:["PyTorch","Segmentation","Classification","GeoPandas"],repo:"https://github.com/tushar2159/semantic-segmentation-pipeline"},
  {id:"philippines",name:"Farm Boundary & Crop Type Intelligence",region:"Philippines · Southeast Asia",icon:"▱",lat:14.5995,lon:120.9842,alt:850000,type:"AGRICULTURE · SEGMENTATION · CLASSIFICATION",description:"Spatial computer-vision workflows for extracting farm boundaries and identifying crop types across heterogeneous agricultural landscapes.",stack:["Satellite Imagery","PyTorch","Rasterio","GIS Outputs"],repo:"https://github.com/tushar2159/semantic-segmentation-pipeline"},
  {id:"nigeria",name:"Tree Crown Detection",region:"Nigeria · West Africa",icon:"♧",lat:9.0765,lon:7.3986,alt:950000,type:"FORESTRY · TREE CROWN DETECTION",description:"High-resolution computer-vision workflows for locating individual tree crowns and generating spatial canopy objects.",stack:["Object Detection","Segmentation","PyTorch","GeoJSON"],repo:"https://github.com/tushar2159/object-detection-pipeline"},
  {id:"kenya",name:"Farm Boundary & Crop Type Intelligence",region:"Kenya · East Africa",icon:"▱",lat:-1.2921,lon:36.8219,alt:900000,type:"AGRICULTURE · SEGMENTATION · CLASSIFICATION",description:"Field-boundary extraction and crop-type intelligence designed for scalable agricultural monitoring and downstream analytics.",stack:["GeoAI","Segmentation","Crop Classification","Spatial Analytics"],repo:"https://github.com/tushar2159/semantic-segmentation-pipeline"},
  {id:"malaysia",name:"Tree Crown Detection",region:"Malaysia · Southeast Asia",icon:"♧",lat:3.139,lon:101.6869,alt:850000,type:"FORESTRY · TREE CROWN DETECTION",description:"Individual tree-crown detection for dense tropical landscapes with spatial post-processing and GIS-ready canopy outputs.",stack:["Deep Learning","Object Detection","Rasterio","GeoPandas"],repo:"https://github.com/tushar2159/object-detection-pipeline"}
];

const viewer = new Cesium.Viewer("globe",{baseLayer:false,terrainProvider:new Cesium.EllipsoidTerrainProvider(),animation:false,timeline:false,baseLayerPicker:false,geocoder:false,homeButton:false,sceneModePicker:false,navigationHelpButton:false,fullscreenButton:false,selectionIndicator:false,infoBox:false,requestRenderMode:false});
viewer.scene.globe.enableLighting=false;viewer.scene.globe.showGroundAtmosphere=true;viewer.scene.skyAtmosphere.show=true;viewer.scene.backgroundColor=Cesium.Color.fromCssColorString("#02060b");
const imagery=viewer.imageryLayers.addImageryProvider(new Cesium.UrlTemplateImageryProvider({url:"https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",credit:new Cesium.Credit("Imagery © Esri"),maximumLevel:19}));
const grid=viewer.imageryLayers.addImageryProvider(new Cesium.GridImageryProvider({color:Cesium.Color.fromCssColorString("#3bb8b0").withAlpha(.18),cellAlpha:.08,backgroundColor:Cesium.Color.TRANSPARENT}));grid.show=false;

const pulseStart=performance.now();
projects.forEach((project,index)=>viewer.entities.add({id:project.id,position:Cesium.Cartesian3.fromDegrees(project.lon,project.lat),point:{pixelSize:new Cesium.CallbackProperty(()=>12+Math.sin((performance.now()-pulseStart)/420+index)*2.5,false),color:Cesium.Color.fromCssColorString("#64f0d8"),outlineColor:Cesium.Color.WHITE,outlineWidth:2,disableDepthTestDistance:Number.POSITIVE_INFINITY},label:{text:project.region.toUpperCase(),font:"700 11px Manrope",fillColor:Cesium.Color.WHITE,showBackground:true,backgroundColor:Cesium.Color.fromCssColorString("#03101b").withAlpha(.82),pixelOffset:new Cesium.Cartesian2(0,-28),distanceDisplayCondition:new Cesium.DistanceDisplayCondition(0,9000000),disableDepthTestDistance:Number.POSITIVE_INFINITY}}));
const route=viewer.entities.add({polyline:{positions:Cesium.Cartesian3.fromDegreesArray(projects.flatMap(p=>[p.lon,p.lat])),width:1.5,material:new Cesium.PolylineGlowMaterialProperty({glowPower:.18,color:Cesium.Color.fromCssColorString("#64f0d8").withAlpha(.65)}),clampToGround:false}});

const missions=document.getElementById("missions");
document.getElementById("missionCount").textContent=`${String(projects.length).padStart(2,"0")} locations`;
missions.innerHTML=projects.map(p=>`<button class="mission" data-id="${p.id}"><i>${p.icon}</i><span><b>${p.name}</b><small>${p.region}</small></span><span>›</span></button>`).join("");
function showProject(project,fly=true){document.querySelectorAll(".mission").forEach(b=>b.classList.toggle("active",b.dataset.id===project.id));document.getElementById("projectType").textContent=project.type;document.getElementById("projectTitle").textContent=project.name;document.getElementById("projectDescription").textContent=project.description;document.getElementById("projectStack").innerHTML=project.stack.map(s=>`<span>${s}</span>`).join("");const demo=document.getElementById("projectDemo");demo.hidden=!project.demo;if(project.demo)demo.href=project.demo;document.getElementById("projectRepo").href=project.repo;document.getElementById("projectCard").classList.add("open");document.getElementById("statusTitle").textContent=project.region.toUpperCase();document.getElementById("statusDetail").textContent=project.type;if(fly)viewer.camera.flyTo({destination:Cesium.Cartesian3.fromDegrees(project.lon,project.lat,project.alt),duration:2.2,orientation:{heading:0,pitch:Cesium.Math.toRadians(-62),roll:0}})}
missions.addEventListener("click",e=>{const button=e.target.closest(".mission");if(button)showProject(projects.find(p=>p.id===button.dataset.id))});document.getElementById("closeCard").addEventListener("click",()=>document.getElementById("projectCard").classList.remove("open"));
const handler=new Cesium.ScreenSpaceEventHandler(viewer.scene.canvas);handler.setInputAction(movement=>{const picked=viewer.scene.pick(movement.position);if(picked?.id?.id){const project=projects.find(p=>p.id===picked.id.id);if(project)showProject(project)}} ,Cesium.ScreenSpaceEventType.LEFT_CLICK);

let rotating=true;viewer.clock.shouldAnimate=true;viewer.clock.onTick.addEventListener(()=>{if(rotating&&viewer.camera.positionCartographic.height>2500000)viewer.camera.rotate(Cesium.Cartesian3.UNIT_Z,-0.00028)});
document.querySelector(".layers").addEventListener("click",e=>{const button=e.target.closest("button");if(!button)return;button.classList.toggle("active");const enabled=button.classList.contains("active");if(button.dataset.layer==="imagery")imagery.show=enabled;if(button.dataset.layer==="network")route.show=enabled;if(button.dataset.layer==="atmosphere"){viewer.scene.skyAtmosphere.show=enabled;viewer.scene.globe.showGroundAtmosphere=enabled}if(button.dataset.layer==="rotation")rotating=enabled});
viewer.camera.setView({destination:Cesium.Cartesian3.fromDegrees(42,18,18500000),orientation:{heading:0,pitch:Cesium.Math.toRadians(-90),roll:0}});
viewer.scene.postRender.addEventListener(()=>{const c=viewer.camera.positionCartographic;document.getElementById("coordinates").textContent=`${Cesium.Math.toDegrees(c.latitude).toFixed(2)}° · ${Cesium.Math.toDegrees(c.longitude).toFixed(2)}° · ${Math.round(c.height/1000).toLocaleString()} km`});
